{% set name = "gwyfile" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf72fedd6af15c952067dbbe87978a4a6262b4e2cd3aa9f2e7bee4ced4071e40

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - six

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - gwyfile

about:
  home: https://github.com/tuxu/gwyfile
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: 'A pure Python interface to reading and writing `Gwyddion
<hhttp://www.gwyddion.net/>`_. files.'
  doc_url: https://github.com/tuxu/gwyfile
  dev_url: https://github.com/tuxu/gwyfile

extra:
  recipe-maintainers:
    - carlodri
