travis:
  secure:
    BINSTAR_TOKEN: FVTZ6Tv6+NveFVatLeCWk8SDcLvc1zmbBhc0H3Q+6gTS3A515DWicd2TgndT0e/+h9NCerC71DjWllewFprZq70hXA5tPpiKaqHRH1eEx73hD9Prih4jPY05+CCM/Z1P5ZfnnvePMmGQ2bPXMpIWcYHg4XSCqs+bLeFe8en8hxqXJ7+nifO2rbnMfpiQKOdRnqzbCGpyGvttFllbg8XT9kq6kmg4c3Sql1tDFWexOxYVTICZBmOESHa24r08SDnIkRjtfKsCtv9b2aumlhHmqBFD+YM6oOtHhwAc0QJ1klVFljp/YswCspMoHchwB692Fv6H4c2hbtdL7oP5bapDxEOTgvTet/bWiZpHkstWKk81BK1yyQ3XiSk/fsVmmRaTceoApL2o1cVmAI0fqtAmpZioMlsWDHlN4DrdgovFv14CywuksszESXbuGoUj6Yd/NOJcl869fTNoqi/xMSa6RN9Zy78henO/znG1kL38Nl0V4hB6zA3NiTaURZUGHv7n7fJqajYDpYLLbkYEqce/fas8HmQfanqjdXSO7r01G+29dSucQP2kIMkqzmUVavnmegfn8GdsKj97U735E/nVsSuS9SzPSPQYh8mJhFyX+0kvhJ/+XWZSrtgn7y4hf8LTz4Y9KxgHRAhSVu/S0RWzbPPsKhpqQZ+++PsAALReV0s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
